# Generated by Django 4.1.4 on 2022-12-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iProcessing', '0002_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='images'),
        ),
    ]
