# Generated by Django 4.1.4 on 2022-12-18 05:46

from django.db import migrations, models
import functools
import iProcessing.models


class Migration(migrations.Migration):

    dependencies = [
        ('iProcessing', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=functools.partial(iProcessing.models._update_filename, *(), **{'path': 'images'})),
        ),
    ]
